name: 'Publish Package'

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 8

      - name: Restore Dependencies
        shell: bash
        run: dotnet restore

      - name: Restore Tools
        shell: bash
        run: dotnet tool restore

      - name: Publish to Thunderstore
        run: dotnet pack "$PROJECT_FILE" -c Release -p:PublishTS=true --no-restore
        env:
          THUNDERSTORE_TOKEN: ${{ secrets.TCLI_AUTH_TOKEN }}
          PROJECT_FILE: ${{ env.PROJECT_FILE }}